use_frameworks!

platform :ios, '8.0'

target 'MGZPersonPrefrenceKit_Example' do
  pod 'MGZPersonPrefrenceKit', :path => '../'

  target 'MGZPersonPrefrenceKit_Tests' do
    inherit! :search_paths

    
  end
end
